version: 2.1
jobs:
  build_slides:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install graphviz
          command: |
            apt update
            apt-get --assume-yes install graphviz
      - run:
          name: Build slides
          command: python hovercraft-graphviz.py gdg-tea.rst build
      - run:
          name: Disable Jekyll
          command: touch build/.nojekyll
      - persist_to_workspace:
          root: .
          paths:
              - .
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@mishkun"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - 'bc:3c:4e:87:aa:46:91:08:3b:4e:82:c5:8d:c7:b7:74'
      - run:
          name: Deploy slides to gh-pages branch
          command: gh-pages --dist build
workflows:
  version: 2
  build_deploy:
    jobs:
      - build_slides:
          filters:
            branches:
              ignore: gh-pages
      - docs-deploy:
          requires:
            - build_slides
          filters:
            branches:
              only: master
